// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhdjatldrffgnkzbwrmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZGphdGxkcmZmZ25remJ3cm14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1ODA2MzYsImV4cCI6MjA2MDE1NjYzNn0.dOW7_q1J69UhUyymvwa7BMIlh6SyWqHccv36pDd_8hM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);